name: Tests
on: [push]

jobs:
  build:
    name: Run Python Tests
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Python virtualenv
      run: |
        python3 -m pip install virtualenv
        ./init_venv.bash
        source venv/bin/activate

    - name: Test with pytest
      run: |
        source venv/bin/activate
        python3 -m pytest --exitfirst --verbose --failed-first \
        --cov=. --cov-report html
